### ISSUE TITLE
TypeError: Path must be a string

### ISSUE THREAD

**Issue by lcjnil** [jonschlinkert/cwd#3]
The document says 
`cwd(['one', 'two.js']);`

but we got

```
> cwd(['one', 'two.js'])
TypeError: Path must be a string. Received [ 'one', 'two.js' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at module.exports (/Users/skyline/.trymodule/node_modules/cwd/index.js:28:23)
    at repl:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:101:20)
```

**Comment by jonschlinkert** [comment]
The docs are wrong, a [list of arguments](https://github.com/jonschlinkert/cwd/blob/master/index.js#L31) is supported, but not an array. 

we could change that code to something like:

``` js
  if (arguments.length > 1 || Array.isArray(filename)) {
    var args = [].concat.apply([], [].slice.call(arguments));
    filepath = path.resolve.apply(path, args);
  }
```

want to do a pr? or I can update as soon as I have a chance. thanks for the issue
